import { AlertTriangle, CheckCircle2, FileJson, RotateCcw, UploadCloud } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { SectionCard } from "@/components/ui/Cards";
import { useToast } from "@/components/ui/toast-context";
import { api } from "@/lib/api";
import { usePermissions } from "@/services/queries";

type RestoreResult = {
  dryRun: boolean;
  mode: "merge-only";
  inserted: Record<string, number>;
  skippedExisting: Record<string, number>;
  conflicts: { collection: string; identifier: string; reason: string }[];
};

export function SystemRestorePage() {
  const permissions = usePermissions();
  const toast = useToast();
  const [fileName, setFileName] = useState("");
  const [payload, setPayload] = useState<unknown>(null);
  const [preview, setPreview] = useState<RestoreResult | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [busy, setBusy] = useState(false);

  const previewInsertTotal = useMemo(
    () => Object.values(preview?.inserted || {}).reduce((sum, value) => sum + value, 0),
    [preview]
  );
  const skippedTotal = useMemo(
    () => Object.values(preview?.skippedExisting || {}).reduce((sum, value) => sum + value, 0),
    [preview]
  );

  if (!permissions.isMasterAdmin) {
    return (
      <main>
        <PageHeader title="System Restore" description="Backup restore is restricted to Master Admin." />
        <div className="p-4 sm:p-6">
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">You do not have permission to restore system data.</div>
        </div>
      </main>
    );
  }

  async function selectFile(file: File | undefined) {
    setPreview(null);
    setConfirmation("");
    if (!file) {
      setFileName("");
      setPayload(null);
      return;
    }
    if (!file.name.toLowerCase().endsWith(".json")) {
      toast.error("Choose a JSON backup generated by this portal.");
      return;
    }
    try {
      const text = await file.text();
      const parsed = JSON.parse(text) as unknown;
      setFileName(file.name);
      setPayload(parsed);
      toast.success("Backup loaded", "Run validation before restoring any records.");
    } catch {
      setPayload(null);
      setFileName("");
      toast.error("The selected file is not valid JSON.");
    }
  }

  async function runRestore(dryRun: boolean) {
    if (!payload) return toast.error("Select a backup JSON file first.");
    if (!dryRun && confirmation !== "RESTORE_MERGE") {
      return toast.error("Type RESTORE_MERGE exactly before applying a restore.");
    }
    setBusy(true);
    try {
      const result = await api<RestoreResult>("/api/import/restore", {
        method: "POST",
        body: JSON.stringify({ payload, dryRun, confirmation: dryRun ? undefined : confirmation })
      });
      setPreview(result);
      if (dryRun) toast.success("Restore validation complete", "No production data was changed.");
      else toast.success("Merge-only restore completed", "Existing records were left untouched.");
    } catch (error) {
      toast.error("Restore failed", error instanceof Error ? error.message : "The backup could not be processed.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <main className="space-y-6 pb-12">
      <PageHeader title="System Backup Restore" description="Validate and merge a portal backup without overwriting or deleting existing production records." />
      <div className="space-y-6 px-4 sm:px-6">
        <div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
          <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" />
          <div>
            <p className="font-bold">Restore is intentionally merge-only.</p>
            <p className="mt-1 text-xs leading-5">The server validates the backup version, previews every collection first, skips records that already exist, and never performs a destructive overwrite or delete.</p>
          </div>
        </div>

        <SectionCard title="1. Select Backup" description="Use a version 2 JSON file downloaded from Import / Export → System Backup.">
          <label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-6 text-center transition hover:border-brand-red hover:bg-red-50/30">
            <UploadCloud className="h-8 w-8 text-brand-red" />
            <span className="mt-3 text-sm font-bold text-slate-800">Choose backup JSON</span>
            <span className="mt-1 text-xs text-slate-500">{fileName || "No file selected"}</span>
            <input className="sr-only" type="file" accept="application/json,.json" onChange={(event) => void selectFile(event.target.files?.[0])} />
          </label>
          <div className="mt-4 flex flex-wrap gap-2">
            <Button type="button" onClick={() => void runRestore(true)} disabled={!payload || busy}>
              <FileJson className="h-4 w-4" />
              {busy ? "Validating..." : "Validate / Dry Run"}
            </Button>
          </div>
        </SectionCard>

        {preview ? (
          <SectionCard title="2. Validation Result" description={preview.dryRun ? "Preview only — no database writes were made." : "Restore execution result."}>
            <div className="grid gap-3 sm:grid-cols-3">
              <Metric label="Eligible to insert" value={previewInsertTotal} />
              <Metric label="Existing records skipped" value={skippedTotal} />
              <Metric label="Conflicts" value={preview.conflicts.length} />
            </div>
            <div className="mt-5 overflow-x-auto">
              <table className="w-full min-w-[620px] text-left text-xs">
                <thead><tr className="border-b border-slate-200 text-slate-500"><th className="p-3">Collection</th><th>Insert</th><th>Skip Existing</th></tr></thead>
                <tbody>{Object.keys(preview.inserted).map((key) => <tr key={key} className="border-b border-slate-100"><td className="p-3 font-semibold text-slate-800">{key}</td><td>{preview.inserted[key] || 0}</td><td>{preview.skippedExisting[key] || 0}</td></tr>)}</tbody>
              </table>
            </div>
            {preview.conflicts.length ? (
              <div className="mt-5 rounded-lg border border-red-200 bg-red-50 p-4">
                <p className="text-sm font-bold text-red-800">Conflicts require review</p>
                <div className="mt-2 max-h-56 space-y-2 overflow-y-auto text-xs text-red-700">
                  {preview.conflicts.slice(0, 100).map((item, index) => <p key={`${item.collection}-${item.identifier}-${index}`}><span className="font-semibold">{item.collection}</span> / {item.identifier}: {item.reason}</p>)}
                </div>
              </div>
            ) : (
              <div className="mt-5 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4" />Backup structure validated without conflicts.</div>
            )}
          </SectionCard>
        ) : null}

        {preview?.dryRun ? (
          <SectionCard title="3. Confirm Merge Restore" description="Execution requires an explicit confirmation phrase. Existing records remain unchanged.">
            <div className="max-w-xl">
              <label className="block text-sm font-semibold text-slate-700">
                Type RESTORE_MERGE
                <Input className="mt-1.5 font-mono" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" />
              </label>
              <Button type="button" className="mt-4" onClick={() => void runRestore(false)} disabled={confirmation !== "RESTORE_MERGE" || busy}>
                <RotateCcw className="h-4 w-4" />
                {busy ? "Restoring..." : "Apply Merge-Only Restore"}
              </Button>
            </div>
          </SectionCard>
        ) : null}
      </div>
    </main>
  );
}

function Metric({ label, value }: { label: string; value: number }) {
  return <div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div>;
}

export default SystemRestorePage;
